### ISSUE TITLE
Strukturering af primary-sidebar

### ISSUE THREAD

**Issue by panelDrive** [theiscnp/pdWaffle#21]
Sidebaren skal kunne vises og tildeles et "setup" under panelSetups, f.eks efter “Department” ( marketing, sales, support ), “userGroup” ( admin, management, developer relateret ), og så lave System extensions i bunden som panel Manager og pdAdmin, og så Primære i toppen som Dashboard, og så lave “Favorites” lige under Primære.

**Comment by theiscnp** [comment]
Du skal blive bedre til at specificere hvad du mener :-)
 - Men jeg tror godt jeg forstår dig:
Du vil opdele menuen i sektioner; primær-punkter i toppen, 'Favorites' derefter, efterfulgt af en sektion med en række punkter/ext.s (defineret ud fra et setup - det oprettes som seperat issue) - og så system punkter/extensions i bunden..

 - Det med at definere et menu-setup for en given bruger-gruppe/department, vil jeg mene vi kan med eksisterende funktionalitet i panelManager->Panel Users
