### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by theiscnp** [theiscnp/pdWaffle#3]
Hoved-funktionaliteter opsættes/udvikles - andre disable's

**Comment by panelDrive** [comment]
Post internt på Dashboard Stream virker ikke.

**Comment by panelDrive** [comment]
Team skal kun vise profiler som er tilknyttet et Company panel som personal Users, og kommer derfor til at være autogeneret.

**Comment by panelDrive** [comment]
ObjectManagement -> panelObjects -> PageObjects ( enable / disable ) 

F.eks ville det være lækkert hvis man på AdPine og andre Whitelabel løsninger, ville kunne enable / disable funktionaliter.

**Comment by panelDrive** [comment]
Tilføjelse til Team på Dashboard siden :
Denne fane burde automatisk blive ordnet når vi får lavet memberOf, clientTo, employedAt

**Comment by theiscnp** [comment]
resterende/ovennævnte features tilføjes som seperate opgaver her i waffle.

**Comment by theiscnp** [comment]
det med enable/disable funk. kommer under "in-page UI settings for panelAdmin"
